# Generated by Django 3.0.4 on 2021-05-16 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stripecustomer',
            old_name='stripe_token',
            new_name='stripe_id',
        ),
    ]
